define(function (require) {
    return {
        '1': [
            {
                'sentence': '_lanco',
                'answer': 'b',
                'concept': 'Se escribe con B:Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'li_ro',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_rillante',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'hom_re',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'la_rador',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_lusa',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'esta_lo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_licuo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ro_le',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_ruñir',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ha_lar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ca_le',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'som_ra',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'cu_rir',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ha_lista',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'repú_lica',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'pu_licista',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'dia_lura',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'nie_la',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_loque',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ama_le',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'sa_le',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'pue_lo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'ta_la',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_landar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_dominal',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_surdo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_sorber',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_solver',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_dicar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_loquear',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_rir',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_razo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_jeto',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_tener',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_servar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_vio',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'o_stáculo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'so_re',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'co_rar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'a_rigo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'su_terráneo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'su_vención',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'sú_dito',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': 'su_rayar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las palabras en las que b va seguida de cualquier consonante.',
            },
            {
                'sentence': '_icéfalo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_imestral',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_ilítera',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_iznieto',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_imensual',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_idente',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_icameral',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_iforme',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_ifronte',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isectriz',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isabuelo',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_imotor',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isemanal',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isílaba',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_ilingüe',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_ilabial',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_ipolar',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_icolor',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isagra',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': '_isexual',
                'answer': 'b',
                'concept': 'Se escribe con B: Las partículas bi, bis, biz (que significan dos o dos veces).',
            },
            {
                'sentence': 'ám_ar',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'ambiguo',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            {
                'sentence': 'am_ulancia',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'cum_re',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'com_inación',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'em_estir',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'em_udo',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'cam_oyano',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'cam_io',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'am_icionar',
                'answer': 'b',
                'concept': 'Se escribe siempre B: Después de m.',
            },
            {
                'sentence': 'ad_ertencia',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_ersidad',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_iento',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_enedizo',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_enir',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_ersión',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_encionar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_ertir',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_ejecer',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_iar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_anecer',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_asión',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_ierno',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_entar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_eniencia',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_ulsión',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_encer',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_oltorio',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_idia',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_estigación',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_alidez',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_alencia',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_idado',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_ención',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'sub_ariedad',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_ertir',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_erbio',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'ad_ersario',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_ainar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'en_ilecer',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_ariable',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'in_encible',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_ersación',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'con_ocar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de las consonantes b, d, y n.',
            },
            {
                'sentence': 'pol_o',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'pol_orín',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'vol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'desenvol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'envol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'revol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'devol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'ol_ido',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'ol_idar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'inol_idable',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'ol_idadizo',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'ol_idado',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'disol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'resol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'sol_entar',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'disol_ente',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'sol_encia',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'absol_er',
                'answer': 'v',
                'concept': 'Se escribe V: Después de ol.',
            },
            {
                'sentence': 'e_acuación',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_angelista',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_aporable',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_asión',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_entual',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_idencia',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_itable',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_ocación',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'e_olucionar',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'para_iana',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'para_a',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pre_ención',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pre_enir',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pre_entiva',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pre_iamente',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pre_aricador',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pri_ilegio',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pri_ación',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            },
            {
                'sentence': 'pro_ocación',
                'answer': 'v',
                'concept': 'Se escribe V: Los comienzos de palabra en eva, eve, evi y evo.',
            }
        ],
        '1000': [
            {
                'sentence': 'Tus ----- fueron embargados.',
                'op1': 'vienes',
                'op2': 'bienes',
                'op1_concept': 'de venir',
                'op2_concept': 'caudal, fortuna',
                'answer': 'bienes',
            },
            {
                'sentence': '¿Me puedes comprar una ----- para mi auto?',
                'op1': 'bobina',
                'op2': 'bovina',
                'op1_concept': 'cilindro de hilo, cordel',
                'op2_concept': 'perteneciente o relativo al toro o a la vaca',
                'answer': 'bobina',
            },
            {
                'sentence': 'No ----- al perro.',
                'op1': 'veces',
                'op2': 'besés',
                'op1_concept': 'plural de vez',
                'op2_concept': 'de besar',
                'answer': 'besés',
            },
            {
                'sentence': 'Para hacer una torta de chocolate, ----- bien sus ingredientes.',
                'op1': 'convino',
                'op2': 'combino',
                'op1_concept': 'de convenir, concordar',
                'op2_concept': 'de combinar, armonizar elementos',
                'answer': 'combino',
            },
            {
                'sentence': 'Las azañas del ----- fueron premiadas.',
                'op1': 'cabo',
                'op2': 'cavo',
                'op1_concept': 'individuo de la clase de tropa, inmediatamente superior al soldado',
                'op2_concept': 'de cavar',
                'answer': 'cabo',
            },
            {
                'sentence': 'El -----  visita su palacio cada año.',
                'op1': 'varón',
                'op2': 'barón',
                'op1_concept': 'persona del sexo masculino',
                'op2_concept': 'título nobiliario',
                'answer': 'barón',
            },
            {
                'sentence': 'Su carácter era muy -----.',
                'op1': 'acerbo',
                'op2': 'acervo',
                'op1_concept': 'áspero, cruel, riguroso',
                'op2_concept': 'montón, conjunto de cosas',
                'answer': 'acerbo',
            },
            {
                'sentence': 'Los barberos de hoy no usan ya la -----.',
                'op1': 'bacía',
                'op2': 'vacía',
                'op1_concept': 'vasija que utilizaban los bareros para remojar la barba',
                'op2_concept': 'desocupada, sin contenido',
                'answer': 'bacía',
            },
            {
                'sentence': 'No quiero que ---- el corderito; da pesar oírlo.',
                'op1': 'vale',
                'op2': 'bale',
                'op1_concept': 'de valer, documento comercial',
                'op2_concept': 'de balar, dar balidos, gemir, berrear, lamentarse, quejarse',
                'answer': 'bale',
            },
            {
                'sentence': 'En una ----- navegaron por el río hasta su desembocadura.',
                'op1': 'valsa',
                'op2': 'balsa',
                'op1_concept': 'de valsar, bailar valses',
                'op2_concept': 'embarcación plana',
                'answer': 'balsa',
            },
            {
                'sentence': 'El ----- es un metal que se oxida rapidamente.',
                'op1': 'vario',
                'op2': 'bario',
                'op1_concept': 'diverso, mudable',
                'op2_concept': 'metal blanco, difícil de fundir',
                'answer': 'bario',
            },
            {
                'sentence': 'Desde el mirador, se contempla un ----- paisaje.',
                'op1': 'bello',
                'op2': 'vello',
                'op1_concept': 'hermoso',
                'op2_concept': 'pelo suave que cubre el cuerpo humano',
                'answer': 'bello',
            },
            {
                'sentence': 'Para afirmarlo, me ----- en poderosas razones.',
                'op1': 'vaso',
                'op2': 'baso',
                'op1_concept': 'recipiente para líquidos',
                'op2_concept': 'del verbo basar, fundar, apoyar',
                'answer': 'baso',
            },
            {
                'sentence': 'Ya eres mayor de edad y puedes -----.',
                'op1': 'votar',
                'op2': 'botar',
                'op1_concept': 'emitir el voto',
                'op2_concept': 'arrojar, tirar',
                'answer': 'votar',
            },
            {
                'sentence': 'Cuando ----- el agua, agrega el café.',
                'op1': 'hierba',
                'op2': 'hierva',
                'op1_concept': 'planta, pasto',
                'op2_concept': 'de hervir',
                'answer': 'hierva',
            },
            {
                'sentence': 'El que ----- la tierra encontrará el tesoro.',
                'op1': 'cave',
                'op2': 'cabe',
                'op1_concept': 'de cavar',
                'op2_concept': 'de caber',
                'answer': 'cave',
            },
            {
                'sentence': 'El niño está ----- en el hospital.',
                'op1': 'grabe',
                'op2': 'grave',
                'op1_concept': 'captar y almacenar imágenes o sonidos.',
                'op2_concept': 'enfermo, que puede ser peligroso o perjudicial',
                'answer': 'grave',
            },
            {
                'sentence': 'El médico ordenó que no comiera carne de -----.',
                'op1': 'vaca',
                'op2': 'baca',
                'op1_concept': 'hembra del toro',
                'op2_concept': 'parte superior de un carruaje',
                'answer': 'vaca',
            },
            {
                'sentence': 'Isabel está propuesta para el cargo ----- que hay en la secretaría.',
                'op1': 'vacante',
                'op2': 'bacante',
                'op1_concept': 'empleo o cargo no ocupado',
                'op2_concept': 'sacerdotisa de Baco',
                'answer': 'vacante',
            },
            {
                'sentence': 'Anielka no ----- en sus respuestas.',
                'op1': 'bacilo',
                'op2': 'vaciló',
                'op1_concept': 'bacteria',
                'op2_concept': 'de vacilar, titubear',
                'answer': 'vaciló',
            },
            {
                'sentence': 'Por ser el ------ del rey, muchos le tenían envidia.',
                'op1': 'balido',
                'op2': 'valido',
                'op1_concept': 'voz de las obejas, corderos',
                'op2_concept': 'favorito de un príncipe o gobernante',
                'answer': 'valido',
            },
            {
                'sentence': 'Marcelo tiene una funda de ----- para su pistola.',
                'op1': 'vaqueta',
                'op2': 'baqueta',
                'op1_concept': 'piel curtida de vaca',
                'op2_concept': 'varilla para limpiar armas',
                'answer': 'vaqueta',
            },
            {
                'sentence': 'El labrador usa una ----- para arar sus campos.',
                'op1': 'esteba',
                'op2': 'esteva',
                'op1_concept': 'hierba, planta',
                'op2_concept': 'pieza del arado que empuña el labrador',
                'answer': 'esteva',
            },
            {
                'sentence': 'Estaba bien repleto de utensilios aquel -----; se veía que era de una cocina bien dotada.',
                'op1': 'basar',
                'op2': 'vasar',
                'op1_concept': 'asentar algo sobre bases, fundamentar, apoyar',
                'op2_concept': 'lugar en cocinas o despensas para colocar platos, vasos',
                'answer': 'vasar',
            },
            {
                'sentence': 'A un pueblo pequeño se le llama también -----.',
                'op1': 'villar',
                'op2': 'billar',
                'op1_concept': 'pueblo pequeño',
                'op2_concept': 'juego de salón',
                'answer': 'villar',
            },
            {
                'sentence': 'El ----- cantó a la Patria con acentos sublimes.',
                'op1': 'bate',
                'op2': 'vate',
                'op1_concept': 'de batir',
                'op2_concept': 'poeta, adivino',
                'answer': 'vate',
            },
        ],

    };
});