define(function (require) {
    return {
        '1': [
            {
                'sentence': 'Tus ----- fueron embargados.',
                'op1': 'vienes',
                'op2': 'bienes',
                'op1_concept': 'de venir',
                'op2_concept': 'caudal, fortuna',
                'answer': 'bienes',
            },
            {
                'sentence': '¿Me puedes comprar una ----- para mi auto?',
                'op1': 'bobina',
                'op2': 'bovina',
                'op1_concept': 'cilindro de hilo, cordel',
                'op2_concept': 'perteneciente o relativo al toro o a la vaca',
                'answer': 'bobina',
            },
            {
                'sentence': 'No ----- al perro.',
                'op1': 'veces',
                'op2': 'besés',
                'op1_concept': 'plural de vez',
                'op2_concept': 'de besar',
                'answer': 'besés',
            },
            {
                'sentence': 'Para hacer una torta de chocolate, ----- bien sus ingredientes.',
                'op1': 'convino',
                'op2': 'combino',
                'op1_concept': 'de convenir, concordar',
                'op2_concept': 'de combinar, armonizar elementos',
                'answer': 'combino',
            },
            {
                'sentence': 'Las azañas del ----- fueron premiadas.',
                'op1': 'cabo',
                'op2': 'cavo',
                'op1_concept': 'individuo de la clase de tropa, inmediatamente superior al soldado',
                'op2_concept': 'de cavar',
                'answer': 'cabo',
            },
            {
                'sentence': 'El -----  visita su palacio cada año.',
                'op1': 'varón',
                'op2': 'barón',
                'op1_concept': 'persona del sexo masculino',
                'op2_concept': 'título nobiliario',
                'answer': 'barón',
            },
            {
                'sentence': 'Su carácter era muy -----.',
                'op1': 'acerbo',
                'op2': 'acervo',
                'op1_concept': 'áspero, cruel, riguroso',
                'op2_concept': 'montón, conjunto de cosas',
                'answer': 'acerbo',
            },
            {
                'sentence': 'Los barberos de hoy no usan ya la -----.',
                'op1': 'bacía',
                'op2': 'vacía',
                'op1_concept': 'vasija que utilizaban los bareros para remojar la barba',
                'op2_concept': 'desocupada, sin contenido',
                'answer': 'bacía',
            },
            {
                'sentence': 'No quiero que ----el corderito; da pesar oírlo.',
                'op1': 'vale',
                'op2': 'bale',
                'op1_concept': 'de valer, documento comercial',
                'op2_concept': 'de balar, dar balidos, gemir, berrear, lamentarse, quejarse',
                'answer': 'bale',
            },
            {
                'sentence': 'En una ----- navegaron por el río hasta su desembocadura.',
                'op1': 'valsa',
                'op2': 'balsa',
                'op1_concept': 'de valsar, bailar valses',
                'op2_concept': 'embarcación plana',
                'answer': 'balsa',
            },
            {
                'sentence': 'El ----- es un metal que se oxida rapidamente.',
                'op1': 'vario',
                'op2': 'bario',
                'op1_concept': 'diverso, mudable',
                'op2_concept': 'metal blanco, difícil de fundir',
                'answer': 'bario',
            },
            {
                'sentence': 'Desde el mirador, se contempla un ----- paisaje.',
                'op1': 'bello',
                'op2': 'vello',
                'op1_concept': 'hermoso',
                'op2_concept': 'pelo suave que cubre el cuerpo humano',
                'answer': 'bello',
            },
            {
                'sentence': 'Para afirmarlo, me ----- en poderosas razones.',
                'op1': 'vaso',
                'op2': 'baso',
                'op1_concept': 'recipiente para líquidos',
                'op2_concept': 'del verbo basar, fundar, apoyar',
                'answer': 'baso',
            },
            {
                'sentence': 'Ya eres mayor de edad y puedes -----.',
                'op1': 'votar',
                'op2': 'botar',
                'op1_concept': 'emitir el voto',
                'op2_concept': 'arrojar, tirar',
                'answer': 'votar',
            },
            {
                'sentence': 'Cuando ----- el agua, agrega el café.',
                'op1': 'hierba',
                'op2': 'hierva',
                'op1_concept': 'planta, pasto',
                'op2_concept': 'de hervir',
                'answer': 'hierva',
            },
            {
                'sentence': 'El que ----- la tierra encontrará el tesoro.',
                'op1': 'cave',
                'op2': 'cabe',
                'op1_concept': 'de cavar',
                'op2_concept': 'de caber',
                'answer': 'cave',
            },
            {
                'sentence': 'El niño está ----- en el hospital.',
                'op1': 'grabe',
                'op2': 'grave',
                'op1_concept': 'captar y almacenar imágenes o sonidos.',
                'op2_concept': 'enfermo, que puede ser peligroso o perjudicial',
                'answer': 'grave',
            },
            {
                'sentence': 'El médico ordenó que no comiera carne de -----.',
                'op1': 'vaca',
                'op2': 'baca',
                'op1_concept': 'hembra del toro',
                'op2_concept': 'parte superior de un carruaje',
                'answer': 'vaca',
            },
            {
                'sentence': 'Isabel está propuesta para el cargo ----- que hay en la secretaría.',
                'op1': 'vacante',
                'op2': 'bacante',
                'op1_concept': 'empleo o cargo no ocupado',
                'op2_concept': 'sacerdotisa de Baco',
                'answer': 'vacante',
            },
            {
                'sentence': 'Anielka no ----- en sus respuestas.',
                'op1': 'bacilo',
                'op2': 'vacilo',
                'op1_concept': 'bacteria',
                'op2_concept': 'de vacilar, titubear',
                'answer': 'vacilo',
            },
            {
                'sentence': 'Por ser el ------ del rey, muchos le tenían envidia.',
                'op1': 'balido',
                'op2': 'valido',
                'op1_concept': 'voz de las obejas, corderos',
                'op2_concept': 'favorito de un príncipe o gobernante',
                'answer': 'valido',
            },
            {
                'sentence': 'Marcelo tiene una funda de ----- para su pistola.',
                'op1': 'vaqueta',
                'op2': 'baqueta',
                'op1_concept': 'piel curtida de vaca',
                'op2_concept': 'varilla para limpiar armas',
                'answer': 'vaqueta',
            },
            {
                'sentence': 'El labrador usa una ----- para arar sus campos.',
                'op1': 'esteba',
                'op2': 'esteva',
                'op1_concept': 'hierba, planta',
                'op2_concept': 'pieza del arado que empuña el labrador',
                'answer': 'esteva',
            },
            {
                'sentence': 'Estaba bien repleto de utensilios aquel -----; se veía que era de una cocina bien dotada.',
                'op1': 'basar',
                'op2': 'vasar',
                'op1_concept': 'asentar algo sobre bases, fundamentar, apoyar',
                'op2_concept': 'lugar en cocinas o despensas para colocar platos, vasos',
                'answer': 'vasar',
            },
            {
                'sentence': 'A un pueblo pequeño se le llama también -----.',
                'op1': 'villar',
                'op2': 'billar',
                'op1_concept': 'pueblo pequeño',
                'op2_concept': 'juego de salón',
                'answer': 'villar',
            },
            {
                'sentence': 'El ----- cantó a la Patria con acentos sublimes.',
                'op1': 'bate',
                'op2': 'vate',
                'op1_concept': 'de batir',
                'op2_concept': 'poeta, adivino',
                'answer': 'vate',
            },
        ],
        'level_2': [
            {
                'sentence': 'La ___ es bonita',
                'answer': 'casa',
                'concept': 'Sustantivo',
            },
            {
                'sentence': 'Ya le puse el ______ a la caña de pescar.',
                'concept': 'Comida o cosas que simulan serlo',
                'answer': 'cebo',
            },
        ]
    };
});